services:
  - type: web
    name: property-adda-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: property-adda-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: property-adda-db
    plan: starter
    databaseName: propertyadda
    ipAllowList: [] # Allow all IPs